baseURL = "https://www.serverlessdays.me/"
languageCode = "en-au"
title = "ServerlessDays Melbourne"

[params]
    logo = "/images/serverless_logo_melb.png"
    description = "A community based conference focusing on Serverless based platforms and technologies. Melbourne, August 20, 2020"
    mascot = "/images/octo_mascot.svg"
    mascot1 = "/images/owl_mascot.svg"
    mascot2 = "/images/unicorn_mascot.svg"
    mascot3 = "/images/moth_mascot.svg"
    mascot4 = "/images/dino_mascot.svg"
    mascot5 = "/images/anteater_mascot.svg"
    date = "August 20, 2020"
    city = "Melbourne"
    twitter = "ServerlessMEL"
    email = "melbourne@serverlessdays.io"
    backgroundImage = "/images/melbourne3.jpg"
    prospectus = "/ServerlessDays Prospectus Melbourne_v2.pdf"

[[params.dates]]
    date = "February 14, 2020"
    text = "CFP Opens"
    done = true

[[params.dates]]
    date = "February 23, 2020"
    text = "Tickets go on Sale"
    done = true

[[params.dates]]
    date = "May 31, 2020"
    text = "CFP Closes"
    done = false

[[params.dates]]
    date = "July 15, 2020"
    text = "Schedule Announcement"
    done = false
    
[params.venue]
    name = "Deakin Edge, Federation Square"
    link = "https://fedsquare.com/event-space/the-edge"
    map = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3151.7986792209813!2d144.96751751531895!3d-37.81818427975165!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad642b71e5a183b%3A0xb0055a25e2ad1bde!2sDeakin%20Edge%2C%20Fed%20Square!5e0!3m2!1sen!2sau!4v1581853866223!5m2!1sen!2sau"
    text = "The Deakin Edge is a stunning glass theatre offering views across the Yarra River to the Arts Centre, the MCG and Alexandra Gardens, located in the heart of Melbourne's Federation Square."

[params.tickets]
    earlybirdPrice = "$60"
    price = "$75"
    buyLink = "https://buytickets.at/serverlessdaysmelbourne/354118" 
    diversity = "$100"
    diversityLink = "https://diversitytickets.org/en/events/435/"

[[params.sponsors.headline]]
    name = "AWS"
    link = "https://aws.amazon.com/"
    logo = "/images/sponsors/AWS.png"
    width = 200
    confirmed = true

[[params.sponsors.headline]]
    name = "Microsoft Azure"
    link = "https://azure.microsoft.com/en-au/free/"
    logo = "images/sponsors/Azure.png"
    width = 420
    confirmed = true

[[params.sponsors.headline]]
    name = "Contino"
    link = "https://www.contino.io/"
    logo = "images/sponsors/contino-logo.png"
    width = 220 
    confirmed = true

[[params.sponsors.gold]]
    name = "IBM"
    link = "https://www.ibm.com/"
    logo = "images/sponsors/IBM_logoRR_blue60_RGB.gif"
    width = 200
    confirmed = true

[[params.sponsors.gold]]
    name = "Servian"
    link = "https://www.servian.com/"
    logo = "images/sponsors/servian.png"
    width = 200
    confirmed = true

[[params.sponsors.gold]]
    name = "Apptio Cloudability"
    link = "https://www.cloudability.com/"
    logo = "images/sponsors/Apptio_Cloudability_Logo.png"
    width = 200
    confirmed = false

[[params.sponsors.gold]]
    name = "Gitlab"
    link = "https://about.gitlab.com/"
    logo = "images/sponsors/gitlab.png"
    width = 160
    confirmed = false

[[params.sponsors.silver]]
    name = "MongoDB"
    link = "https://www.mongodb.com/"
    logo = "images/sponsors/MongoDB.jpg"
    width = 200
    confirmed = false

[[params.sponsors.silver]]
    name = "Nintex"
    link = "https://www.nintex.com/"
    logo = "images/sponsors/nintex.png"
    width = 200
    confirmed = false

[[params.sponsors.community]]
    name = "Twilio"
    link = "https://www.twilio.com/"
    logo = "images/sponsors/twilio-logo-red.png"
    width = 200
    confirmed = false

[[params.sponsors.community]]
    name = "Just Digital People"
    link = "https://www.justdigitalpeople.com.au/"
    logo = "images/sponsors/justdigitalpeople.jpg"
    width = 200
    confirmed = false

[[params.sponsors.community]]
    name = "YOW!"
    link = "https://yowconference.com/"
    logo = "images/sponsors/yow.png"
    width = 170
    confirmed = false

[params.agendainfo]
    date = "July 15th, 2002"

[[params.agenda]]
    time = "8:00 - 9:00"
    type = "coffee"
    title = "Registration"
[[params.agenda]]
    time = "9:00 - 9:10"
    type = "talk"
    title = "Opening Remarks - Lars Klint"
[[params.agenda]]
    time = "9:10 - 9:40"
    type = "keynote"
    talk = "jeff-hollan"
[[params.agenda]]
    time = "9:45 - 10:15"
    type = "talk"
    talk = "jessica-flanagan"
[[params.agenda]]
    time = "10:20 - 10:35"
    type = "lightning"
    talk = "has-altaiar"
[[params.agenda]]
    time = "10:35 - 10:50"
    type = "lightning"
    talk = "toshinori-sugita"
[[params.agenda]]
    time = "10:50 - 11:10"
    type = "coffee"
    title = "Coffee Break"
[[params.agenda]]
    time = "11:10 - 11:40"
    type = "talk"
    talk = "nelly-sattari"
[[params.agenda]]
    time = "11:45 - 12:15"
    type = "talk"
    talk = "scott-coulton"
[[params.agenda]]
    time = "12:20 - 12:35"
    type = "lightning"
    talk = "effy-elden"
[[params.agenda]]
    time = "12:40 - 13:00"
    type = "lightning"
    talk = "stefano-tempesta"
[[params.agenda]]
    time = "13:00 - 14:00"
    type = "lunch"
    title = "Lunch & Networking"
[[params.agenda]]
    time = "14:00 - 14:30"
    type = "keynote"
    talk = "danilo-poccia"
[[params.agenda]]
    time = "14:35 - 15:05"
    type = "talk"
    talk = "aditi-phadke"
[[params.agenda]]
    time = "15:10 - 15:40"
    type = "talk"
    talk = "aaron-powell"
[[params.agenda]]
    time = "15:40 - 15:55"
    type = "coffee"
    title = "Coffee Break"
[[params.agenda]]
    time = "15:55 - 16:25"
    type = "talk"
    talk = "pratik-khasnabis"
[[params.agenda]]
    time = "16:30 - 17:00"
    type = "talk"
    talk = "samuel-chalela"
[[params.agenda]]
    time = "17:05 - 17:35"
    type = "talk"
    talk = "bret-mcgowan"
[[params.agenda]]
    time = "17:35 - 17:45"
    type = "coffee"
    title = "Closing remarks - Organising Team"
[[params.agenda]]
    time = "18:00 - open end"
    type = "afterparty"
    talk = "afterparty"
    description = "Afterparty at Queensberry Hotel"
