baseURL = "https://www.serverlessdays.me/"
languageCode = "en-au"
title = "ServerlessDays Melbourne"

[params]
    logo = "/images/serverless_logo_melb.png"
    description = "A community based conference focusing on Serverless based platforms and technologies. Melbourne, August 29, 2019"
    mascot = "/images/octo_mascot.png"
    date = "August 29, 2019"
    city = "Melbourne"
    twitter = "ServerlessMEL"
    email = "melbourne@serverlessdays.io"
    backgroundImage = "/images/melbourne2.jpg"
    prospectus = "/Prospectus-v3.pdf"

[[params.dates]]
    date = "April 09, 2019"
    text = "CFP Opens"
    done = true

[[params.dates]]
    date = "April 30, 2019"
    text = "Tickets go on Sale"
    done = true

[[params.dates]]
    date = "June 10, 2019"
    text = "CFP Closes"
    done = true

[[params.dates]]
    date = "July 15, 2019"
    text = "Schedule Announcement"
    done = false
    
[params.venue]
    name = "Melbourne Museum"
    link = "https://museumsvictoria.com.au/melbournemuseum/"
    map = "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12609.740989119078!2d144.9717408!3d-37.803273!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x8f2c10c1546cc221!2sMelbourne+Museum!5e0!3m2!1sen!2sau!4v1554896925628!5m2!1sen!2sau"
    text = "The venue is Melbourne Meuseum, it is a natural and cultural history museum located in the Carlton Gardens in Melbourne, Australia. Located adjacent to the Royal Exhibition Building, it is the largest museum in the Southern Hemisphere."

[params.tickets]
    price = "$60"
    diversityLink = "https://diversitytickets.org/events/371/"

[params.tickets.eventBrite]
    eventid = "55648142091"
    link = "https://www.eventbrite.com/e/serverlessdays-amsterdam-2019-tickets-55648142091"

[[params.sponsors.headline]]
    name = "AWS"
    link = "https://aws.amazon.com/"
    logo = "/images/sponsors/AWS.png"
    width = 200

[[params.sponsors.headline]]
    name = "Microsoft Azure"
    link = "https://azure.microsoft.com/en-au/free/"
    logo = "images/sponsors/Azure.png"
    width = 420 

[[params.sponsors.gold]]
    name = "Servian"
    link = "https://www.servian.com/"
    logo = "images/sponsors/servian.png"
    width = 200

[[params.sponsors.community]]
    name = "Twilio"
    link = "https://www.twilio.com/"
    logo = "images/sponsors/twilio-logo-red.png"
    width = 200

[[params.sponsors.community]]
    name = "Just Digital People"
    link = "https://www.justdigitalpeople.com.au/"
    logo = "images/sponsors/justdigitalpeople.jpg"
    width = 200

[[params.agenda]]
    time = "8:00 - 9:00"
    type = "coffee"
    title = "Registration & Breakfast"
[[params.agenda]]
    time = "9:00 - 9:15"
    type = "coffee"
    title = "Opening Remarks"
[[params.agenda]]
    time = "9:15 - 9:45"
    type = "talk"
    talk = "olaf-conijn"
[[params.agenda]]
    time = "9:50 - 10:20"
    type = "talk"
    talk = "michael-adda"
[[params.agenda]]
    time = "10:25 - 10:55"
    type = "talk"
    talk = "slobodan-stojanovic"
[[params.agenda]]
    time = "10:55 - 11:15"
    type = "coffee"
    title = "Coffee Break"
[[params.agenda]]
    time = "11:15 - 11:45"
    type = "talk"
    talk = "asavari-tayal"
[[params.agenda]]
    time = "11:50 - 12:20"
    type = "talk"
    talk = "eduardo-laureano"
[[params.agenda]]
    time = "12:20 - 13:50"
    type = "lunch"
    talk = "lunch-signing"
[[params.agenda]]
    time = "13:50 - 14:20"
    type = "talk"
    talk = "hen-peretz"
[[params.agenda]]
    time = "14:25 - 14:55"
    type = "talk"
    talk = "ory-segal"
[[params.agenda]]
    time = "14:55 - 15:20"
    type = "coffee"
    title = "Coffee Break"
[[params.agenda]]
    time = "15:20 - 15:50"
    type = "talk"
    talk = "marc-duiker"
[[params.agenda]]
    time = "15:55 - 16:25"
    type = "talk"
    talk = "danilo-poccia"
[[params.agenda]]
    time = "16:30 - 16:40"
    type = "lightning"
    talk = "roberto-diaz"
[[params.agenda]]
    time = "16:40 - 16:50"
    type = "lightning"
    talk = "alessandro-vozza"
[[params.agenda]]
    time = "16:50 - 17:00"
    type = "lightning"
    talk = "henk-waanders"
[[params.agenda]]
    time = "17:00 - 17:10"
    type = "coffee"
    title = "Closing Remarks"
[[params.agenda]]
    time = "17:10 - 18:00"
    type = "coffee"
    title = "Happy Hour & Networking"
[[params.agenda]]
    time = "18:00 - open end"
    type = "afterparty"
    talk = "afterparty"
    description = "Afterparty at Caf√© Delirium"
